### ISSUE TITLE
Using styles

### ISSUE THREAD

**Issue by ismail-codar** [adamhaile/surplus#15]
Using styles like:
```jsx 
<div style={{ width: '100%' } as CSSStyleDeclaration}>test</div>
```

throws `Uncaught TypeError: Surplus.staticStyle is not a function` in runtime. 

And this [input style.width="50%" ](https://github.com/adamhaile/surplus/blob/master/spec/preprocessor/staticproperty.spec.js#L37 ) screenshot is following in vscode editor.

![image](https://user-images.githubusercontent.com/282104/30924436-6529e588-a3b7-11e7-8e3a-a5b4c0281d1f.png)
 style-width way can be preferred

**Comment by adamhaile** [comment]
Thanks again, Ismail!  I was missing an export on the staticStyle runtime function.  Just pushed that.

Yeah, the dotted-path syntax for properties is supported by the Surplus compiler, but it's not actually conformant JSX, so Typescript and any other JSX tool will choke on it.  I had been thinking about either a syntax like `style-width` or `style_width` as a workaround.  `style-width` feels more natural, but it conflicts with the recently added attribute support, which uses the heuristic 'if it has a dash, it's an attribute.'  Hmm, need to think through what might be most natural here.  I'm leaning toward saying:

1. If Surplus can tell you're trying to set a name that only exists as an attribute, then it will issue a node.setAttribute(<name>, <value>) statement instead of node.<name> = <value>.  As far as a I know, the only attributes in this class are the aria-* and data-* attributes.

2. Otherwise, dashes are deep properties and are converted to dots in the output.

**Comment by ismail-codar** [comment]
Looks it is fixed in beta3
