### ISSUE TITLE
Handling typescript generic parameters

### ISSUE THREAD

**Issue by ismail-codar** [adamhaile/surplus#2]
This works
```javascript
const Footer = (props: { leftCount, children?}) => {
    return <div>{props.leftCount()}</div>
}
```
But this is not working. Error: element missing close tag at line......
`DataSignal<number>` is confused with tags.
```javascript
const Footer = (props: { leftCount:DataSignal<number>, children?}) => {
    return <div>{props.leftCount()}</div>
}
```

**Comment by adamhaile** [comment]
Hi Ismail --
Yeah, this is a current limitation of the Surplus preprocessor.  It doesn't understand enough about context to know that `<number>` is a generic type specification, while `<div>` is a JSX tag.

Two possible workarounds:

1. Put a space around number `< number >` (if it's not obvious, that's a space after the `<`).  Surplus preprocessor only kicks in if it sees `<` immediately followed by a tag name.

2. Use `() => number` instead of `DataSignal<number>`.  In my own code, I only use the `DataSignal<>` type when I want to make it clear that I will be setting the value.  If I'm only consuming it, simple `() => number` is sufficient and clearer about intent.  It also means that my code will work fine if `leftCount` later becomes the result of a computation.

Also, you sir, are a brave man for creating Surplus apps with as little documentation as I've put out.  Let me know if you get stuck.  I'm working on getting more info out as soon as I can.

**Comment by ismail-codar** [comment]
Seems to be resolved after last submissions.
