### ISSUE TITLE
Server-side rendering?

### ISSUE THREAD

**Issue by matthew-dean** [adamhaile/surplus#29]
This project looks awesome, and I came across it by looking at js-frameworks-benchmark. One thing that's not clear: since Surplus creates native DOM elements, does that mean it can't pre-render an HTML page and "re-hydrate" it, like other libs (reducing time of first-paint)?

That is, other related questions: what does the root page look like? How is it attached to a document? How are these components consumed? Would be good to have some ideas of how it works in practice. Thanks.

**Comment by adamhaile** [comment]
Great questions.

1. Surplus compiles into DOM API calls.  Some people have done server side rendering by using one of the javascript implementations of the DOM API, like [jsdom](https://github.com/tmpvar/jsdom).  @flagello was working on [endom](https://github.com/flagello/endom) as an optimized implementation for this purpose.  That then generates the HTML string sent to the client.  The plus of this approach is that it works with out-of-the-box surplus.  The downside is that it doesn't really "re-hydrate" on the client side but rather throws away the initial set of nodes and replaces them with the client-side rendered ones.

2. Surplus makes plain DOM nodes, so there's no special "root page" or "mount point" as with vdom libraries.  You attach it to the page with plain DOM commands, like `document.page.appendNode(<h3>hello from surplus</h3>)`.

**Comment by matthew-dean** [comment]
@adamhaile Thanks for the answers!

**Comment by afranchuk** [comment]
For future reference, I did just what @adamhaile suggested and used a server-side DOM implementation to render the pages. Then on the client side I replaced the body contents with the client-side-rendered DOM. In my case, I needed to support systems with JS disabled, but when enabled have live updates on the page, so it worked out well enough. It would be nice to have some way to attach to the existing DOM, as then I wouldn't have to actually re-render the whole thing (which involves packaging the entire server-side state in the generated page), but I realize that that is difficult to do.

I found [domino](https://github.com/fgnass/domino) to be smaller and faster than [jsdom](https://github.com/tmpvar/jsdom) while implementing enough for my requirements. Libraries such as [nodom](https://github.com/redom/nodom), [endom](https://github.com/flagello/endom), and [basichtml](https://github.com/WebReflection/basicHTML) were almost good enough, but some were lacking `createElementNS` while others simply messed up rendering certain elements. I had a need to render `link` and various SVG elements, which seemed to trip up a lot of the libraries.

**Comment by villzor** [comment]
This would indeed make Surplus even more interesting to work with. Afranchuk, would you mind sharing a little more details about how you rendered the Surplus app server side? I tried using JSDOM and executed scripts with Node, but it was way too slow. I now tried your idea now with domino, but I haven't found a good general way of rendering the Surplus application. Did you manage to create something that accepts the entry point to the application somehow?

**Comment by afranchuk** [comment]
Yeah, it is a little more involved than I described. Basically, my main code uses the HTTP request to get the page (so a request to http://{host}/mypage would cause the server to look for {server_root}/pages/mypage.js), and if the page exists it loads it using the node [vm](https://nodejs.org/api/vm.html) module, with a custom (but simple) implementation for the usual node `require()` method. All the web server pages use node-style modules and are loaded with that assumption. They could potentially be run through babel as well. The page that is actually returned to the client contains the same code that has run on the server, and there's a simple implementation of the environment variables that are assumed in that code packaged along as well (such as the presence of `require()`, among other things). Naturally as much is cached as possible, but I still need to re-render to some degree on the server-side due to the constantly changing server-side state.

For production builds, I preprocess all the pages through the Surplus compiler using a custom build script (which again could also run through things like babel if required) and also condense the web server code down to a single bundled file. The deployable production code then becomes about 3MB of web server javascript in a single file, and a bit less than 1MB of javascript and resources for the actual website (of which each page is on average taking ~130kB per request when there's no caching). At that point there are no dependencies: all you need to do is invoke `node server.js`. I had previously been experimenting with [Nuxt.js](https://nuxtjs.org/), but that had a ton of server code that didn't want to easily be packed into a bundled file (although there may be some incantation that pulls it off), and also ended up being a bit slower and bandwidth-heavy per request.

I would like to host this code publicly for people to play around with, but it was done for my job and there may be restrictions on it. I could probably get permission though...

**Comment by afranchuk** [comment]
For any wondering, I've published SSR middleware using surplus at https://github.com/afranchuk/surplus-ssr. It's still rough around the edges and probably doesn't cover every use case. There are a number of desirable improvements (mentioned in the README), but it's given me some good performance and I've gotten a decent amount of use out of it so far.

Maybe if it gets some polish it can be part of the surplus repository (although I think it's fine to keep it separate, too).
