### ISSUE TITLE
Jsx spread attributes

### ISSUE THREAD

**Issue by ismail-codar** [adamhaile/surplus#3]
[Todomvc ](https://github.com/adamhaile/surplus-todomvc) was very useful for me. Thanks for @adamhaile 

Surplus and S.js made me very excited. I think this is the best frontend component library for me and others.  It allready [fastest](https://rawgit.com/krausest/js-framework-benchmark/074dade9f9802cec412c82a47e222c9e3579a83f/webdriver-ts-results/table.html)

I found very few bugs after recent commits. 

In the example below App1 and App2 must be the same. 
https://facebook.github.io/react/docs/jsx-in-depth.html#spread-attributes
```js
function App1() {
    return <Greeting firstName="Ben" lastName="Hector" />;
}

function App2() {
    const props = { firstName: 'Ben', lastName: 'Hector' };
    return <Greeting {...props} />;
}
```
Here is the rendering result. App2 rendering incomplete.
```js
function App1() {
    return Greeting({
        firstName: "Ben",
        lastName: "Hector",
        children: [
            
        ]});
}
function App2() {
    var props = { firstName: 'Ben', lastName: 'Hector' };
    return Greeting({
        
        children: [
            
        ]});
}
```

**Comment by adamhaile** [comment]
Hi @ismail-codar --
Thanks for the report.  Yeah, as you saw with this weekend's commits, I'm just adding support for spread expressions.  Spreads in sub-components is on the list but isn't there yet.  Surplus originally had a slightly different syntax than JSX, and that syntax didn't have spread expressions.  I want to support spreads to facilitate transition to/from existing JSX, but full support isn't there yet.  I'll add a tracking issue to represent the state of progress.

If it helps, you could achieve the same effect with current code by just calling Greeting, since components are just functions in Surplus.  So instead of `return <Greeting {...props} />` you would just do `return Greeting(props)`.  If you're doing it inside a container, you can use an insert: `<div>{Greeting(props)}</div>`.

Thanks for spending time checking out Surplus!
-- Adam

**Comment by ismail-codar** [comment]
Tracking with https://github.com/adamhaile/surplus/issues/4
