### ISSUE TITLE
Browser Support

### ISSUE THREAD

**Issue by gilesbutler** [adamhaile/surplus#30]
Hey guys,

Awesome library, just wondering what the browser support is like? 
Do Surplus and S require any polyfills for old browsers?

Thanks

**Comment by adamhaile** [comment]
No polyfills required.  S is actually ES3, because I want to stay in the set of features that are already well optimized by the engines.  Surplus uses the most basic set of DOM API calls.  If I get a chance, I'll set up one of the automated tests widgets just to verify that there are no surprises.

SArray, a utility library for working with array-valued signals, does use Map, which is IE11+ according to [kangax](https://kangax.github.io/compat-table/es6/#test-Map_basic_functionality).

**Comment by gilesbutler** [comment]
Nice!! Thanks @adamhaile, yeah the Map polyfill is pretty small anyway so that's all good.
