### ISSUE TITLE
fast (but not that fast) input misses last key press

### ISSUE THREAD

**Issue by griebd** [adamhaile/surplus#31]
Hi there, got some time to work on my little project again... :wink:
And I think I found some kind of a bug!

With this code (boilerplate removed):
```javascript
<input type="text" fn={ data(login.user, "keyup") } />
<input type="password" fn={ data(login.password, "keyup") } />
```

If I type `admin` as user and then use the `tab` key I get only `admi` in `login.user`, it happens in more than half the tries (if you just type without pauses). The input field has the full `admin` though.

Thanks, Grieb

**Comment by adamhaile** [comment]
Interesting.  I think the tab defocuses the element before the keyup event fires, meaning it never fires.

If you watch the "input" event instead of "keyup" it should work.  I just repro'd the case using "keyup" but couldn't when using "input".  Give it a shot and let me know if it works for you.

BTW, I'd like to change the behavior of data() to listen to "input" instead of "change", so that the default behavior is synchronous.  Opinions?

**Comment by adamhaile** [comment]
Grieb, I switched the default event in surplus-mixin-data from the 'change' event to the 'input' event, so you shouldn't need to specify an event at all anymore to get the synchronous behavior.
