### ISSUE TITLE
Feature request: hyphenated function properties

### ISSUE THREAD

**Issue by matthew-dean** [adamhaile/surplus#32]
I figured out that I can't do this:
```jsx
        <Callout slash-color="light" text-color="dark">
            This is some copy text.
        </Callout>
```
Since I'm used to working with Vue, I figured that either these attributes would be mapped to:
`{Callout({ slashColor: "light", textColor: "dark", children: [ "This is some copy text" ] })}` OR
`{Callout({ "slash-color": "light", "text-color": "dark", children: [ "This is some copy text" ] })}`.

Instead, Surplus does neither. It fails parsing because of the hyphens. 😢  The main reason I wanted to do this is to reflect attributes in the rendered DOM depending on hyphenated value. But the other reason to do it is to keep the markup consistent. Camelcase attributes look wrong. If I had a preference, I might choose the former, but really either option other than failing parsing would work for me.

**Comment by adamhaile** [comment]
Compiler outputting bad js is no bueno.

Fixed with 375635885591e8e482c1ec263ba595b240a537fc .

I didn't do a hyphen-to-camel-case conversion.  It looks like React preserves the hyphens in component properties, and I figure it's more important to be consistent with that behavior.

Thanks for the report!

**Comment by matthew-dean** [comment]
Can you export a new build?

**Comment by adamhaile** [comment]
Done.
