### ISSUE TITLE
Question: Using Surplus without JSX

### ISSUE THREAD

**Issue by vp2177** [adamhaile/surplus#40]
Is it possible to use Surplus, but without writing JSX?

This would be analogous to using React with manually written `React.createElement()` calls. The benefit is being able to transpile from languages that don't support (and can't preserve) JSX.

**Comment by adamhaile** [comment]
At the moment, no, there's not a good way to do this unfortunately.  Most of Surplus is in the compiler, and the runtime library is small and a servant of the compiler (it just contains what the compiler needs, and changes often to support the compiler).  What language are you working with?  If might be possible to retarget the S compiler to generate code for it.

**Comment by vp2177** [comment]
`OCaml`, compiled via `BuckleScript`. There is a variant, `Reason`, which does support a version of JSX: https://reasonml.github.io/guide/language/jsx/ 
However, compile-to-JS languages are proliferating, so a language-neutral solution would better... If not a stable API, then perhaps separating the "template" into its own file. And compiling that to JS?

Just an idea.

**Comment by brodybits** [comment]
> Is it possible to use Surplus, but without writing JSX?

S.js (<https://github.com/adamhaile/S>)??

**Comment by foucist** [comment]
Can surplus be replaced with babel handling the jsx (i.e /* pragma jsx */ ) and S.js + whatever else in combination ?

**Comment by ismail-codar** [comment]
Currently surplus based own compiler. 
https://github.com/adamhaile/surplus/blob/master/README.md#why-isnt-the-surplus-compiler-built-on-babel

Also you can see my attempt. https://github.com/ismail-codar/fjsx It is surplus inspired backed by babel.

**Comment by adamhaile** [comment]
@foucist I should add a FAQ about this one as it's a good question and it's come up a few times now.

No, Babel's JSX plugin won't work for Surplus.  It produces a different output than Surplus uses.  It's not just trivial inconsistencies:

- The standard compilation format for JSX is designed for use with virtual DOM libraries, not a real DOM library like Surplus (or Ismail's fjsx he linked).  As such, it doesn't support the features we need.  Specifically, we need to capture the dynamic parts of the JSX inside closures so that we can re-run them and do targeted updates to the DOM when data changes.  The standard JSX compilation strategy doesn't wrap them in closures, so it doesn't work for Surplus.

- More generally, part of the design philosophy of Surplus is to do as much of the work at compile time as we can.  It tries to provide a developer-friendly way to construct the DOM -- JSX -- while minimizing the amount of overhead that app's users experience from that abstraction.  So a custom compiler will likely always be a part of Surplus.

It is possible that the Surplus compiler may be adapted to be a Babel plugin, so that we can leverage Babel's existing parser and compilation pipeline.

**Comment by ismail-codar** [comment]
Babel ecosystem has many plugins..  in generally parser and transformer plugins.
Standart jsx parser doing good work can be try online https://astexplorer.net/#/gist/7e8b5d018487a3f828f00741ef8a67f9/88f48ac49bf364bc01673a14ea1bf3bdcf90e782 

Also a transformer plugin can be written for surplus. I think it must be use the code generation strategy of current surplus compiler.

My trial project (fjsx) using [babel-preset-react](https://github.com/babel/babel/tree/master/packages/babel-preset-react) in middleware. Transforms babel-preset-react's output AST to own format. I thought that transformation would be easier and more effective, but I was wrong. Because generated code was a little slow in runtime. Surplus is fastest and I can be migrate it's code generation strategy later time.
