### ISSUE TITLE
if/else or ternary statements

### ISSUE THREAD

**Issue by dyu** [adamhaile/surplus#41]
This doesn't work.
```ts
export interface Greeting {
    msg: string
}
export const GreetingV = ({pojo}: {pojo: Greeting}) =>
<div>
  <b>{pojo.msg}</b>
</div>

export const HelloV = ({pojo}: {pojo: Greeting}) =>
<div>
  <span>{pojo.msg}</span>
</div>
```
```jsx
<div>
${p.disabled ? <HelloV pojo={p.greeting} /> : <GreetingV pojo={p.greeting} />}
</div>
```

Would also be cool if the compiler lazily creates it (and caches) on the expression that evals to true.

**Comment by adamhaile** [comment]
It ought to work.  Here's a CodePen with your code: https://codepen.io/anon/pen/BJQEqv?editors=0010 .

Are you on the beta 0.5 branch or 0.4?

JSX expressions in surplus compile to js expressions, so they should behave the same as js expressions anywhere.  I.e., ternary expressions short-circuit and only evaluate one branch.

**Comment by adamhaile** [comment]
Ah, I see what's going on.  Turns out this has nothing to do with ternary operators.  It's a token parsing error.  The parser was recently updated to understand string template literals.  The tokenizer is mistaking the "${" in your code as a string template literal insertion expression.  If you put a space between $ and { you'll see that it works then.

I'll update the tokenizer to be smarter here.

**Comment by adamhaile** [comment]
Fixed with 9a1165b .  If you have a change, please verify that this resolves your problem.

**Comment by dyu** [comment]
Thanks.

**Comment by adamhaile** [comment]
Thanks for the report!
