### ISSUE TITLE
Component life cycle events strategy

### ISSUE THREAD

**Issue by ismail-codar** [adamhaile/surplus#6]
In the virtual dom environment component life cycle events can be easier. But surplus is different.  At least component attached to DOM and component removed from DOM events is required in real world.

I have developed a solution for now but mozilla [this page](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Mutation_events#Browser_compatibility) says it unperformed. Because DOMNodeRemoved is deprecated and performance problematic. https://github.com/SilentCicero/throw-down is may be another solution.

I think it would be better to solve this problem in the surplus infrastructure.

I'm doing some material design components experiments right now.

##### My current solution
```typescript
import * as Surplus from 'surplus';
Surplus;

const lifeCycle = (options: { created: (node: HTMLElement) => void, removed: (node: HTMLElement) => void }): (node: HTMLElement) => void => {
    return (node) => {
        setTimeout(() => {
            options.created.call(options, node)
            node.parentElement.addEventListener("DOMNodeRemoved", (e) => {
                options.removed.call(options, node)
            })
        })
    }
}

const buttonCreated = (node: HTMLElement) => {
    this.ripple = window["mdc"].ripple.MDCRipple.attachTo(node);
}

const buttonRemoved = (node: HTMLElement) => {
    this.ripple.destroy();
}


export const MdButton = (props) => {
    return <button className="mdc-button mdc-ripple-surface" {...lifeCycle({ created: buttonCreated, removed: buttonRemoved }) }>
        {props.children[0]}
    </button>
}
```
Links: 
[Material design components](https://github.com/material-components/material-components-web/blob/master/docs/integrating-into-frameworks.md)
[Angular example](https://plnkr.co/edit/b4v160c186ErrPG5vNza?p=preview)

**Comment by adamhaile** [comment]
Hi Ismail --
Surplus is designed to have a small and easy to extend core.  Because it returns real dom, you have a lot more power compared to vdom libraries.  In a vdom library, extensions like yours above would likely have to be a part of the core library, but in surplus, you can do it in your own code.  I consider that a feature not a bug :).  I'd rather keep them out of the core and available in libraries.

For what its worth, vdom libraries, at least the ones I know, don't provide the lifecycle hook you're looking for.  React's componentDidMount() doesn't mean that the component was mounted to a parent, it means that the react component and all its children were mounted to real dom nodes.  It means "from here down is mounted" not "from here up."  The node may still be unattached to the parent or, higher up, the page.

In surplus apps, when I've needed things like screen dimensions which can only be gotten once the node is actually in the page, I've used the same logic I do for React apps, which is to put the code behind a requestAnimationFrame() call, kind of like you're doing with setTimeout().

S does, by the way, have a minimal lifecycle hook, in the form of S.cleanup().  Here's one way to maybe go about what you're trying:
```javascript
export const MdButton = (props) => {
    const btn = 
        <button className="mdc-button mdc-ripple-surface">
            {props.children[0]}
        </button>,
        ripple = window["mdc"].ripple.MDCRipple.attachTo(btn);

    S.cleanup(() => ripple.destroy());

    return btn;
}
```
If `MDCRipple.attachTo()` really needs the node to be in the page, you might tweak like this:
```javascript
export const MdButton = (props) => {
    let btn = 
        <button className="mdc-button mdc-ripple-surface">
            {props.children[0]}
        </button>,
        ripple = null as MDCRipple | null;

    requestAnimationFrame(() => ripple = window["mdc"].ripple.MDCRipple.attachTo(btn)); // after rAF
    S.cleanup(() => ripple && ripple.destroy());

    return btn;
}
```
The use of S.cleanup() here assumes that we're constructing the MdButton downstream from either an S.root() or an S() computation.  It will run whenever the computation updates or the root is disposed.  In other words, instead of dom lifecycle events, we're using value lifecycle events: we destroy the ripple resource when the MdButton value is no longer current.

Material design for Surplus sounds cool :).  Let me know if I can help as you explore it.
-- Adam

**Comment by ismail-codar** [comment]
Thank you for your help @adamhaile I tired `S.cleanup` method with my page router and good working. 
When a page is activate S.root is constructuring and page is deactivate calling dispose. Only my recommendation is `S.ondestroy` or `S.destroyed` could have been more intuitive for beginners reather than  `S.cleanup` on naming.

Jquery and after time virtual dom libraries are big steps in the development of web. Currently virtual dom is very popular. I hate virtual dom because various optimizations to make the minimum virtual dom diffing or to do it at every time is bad. 
I think virtual dom will be die and react, angular, vue all of they will die or change dramatically in the future. 
I canceled my own non-virtual dom project because surplus / s-js is best way for me. Easy, lightweight and real reactive. 

Currently i am working on [surplus-material](https://github.com/ismail-codar/surplus-material)
Demo application will be similiar to https://material-components-web.appspot.com/ I will send the POC application soon..

Are you able to try [surplus nativescript entegration example](https://github.com/ismail-codar/surplus-nativescript-template) mentioned in https://github.com/adamhaile/S/issues/2?
