### ISSUE TITLE
Unexpected component recreation

### ISSUE THREAD

**Issue by derekhawker** [adamhaile/surplus#67]
Hi, I've been having an issue with components that are recreated after a signal updates, when they should be reusing the DOM and updating attributes instead. 

I've made a simplified example on jsfiddle to show the issue. I found this issues while using an array of JSX elements as a return type. I think I've seen this a few times before when dealing with sibling JSX. It has caused odd problems in places where I've used props.children if there are multiple sibling used as children.

Demo: http://jsfiddle.net/zd37ahbo/16/

I tried to show the issue with console logging in the {Broken,Fixed}Component. If you open the console, you'll see the message "Should only see this message once" appear each time you click the button. If you replace the usage of BrokenComponent with FixedComponent, you will no longer see that message in the console logs.

I would expect both Broken- and FixedComponent to log just once on creation because the signal is evaluated on an attribute of its return JSX.

I hope this was enough information. Let me know if there's anything I can clarify.

**Comment by derekhawker** [comment]
I wanted to see what you meant so I pulled out the generated Javascript from jsfiddle. I've included it below for anyone else.

Hmm, so I think part of my problem is I may have come away with the wrong expectation from the readme. Specifically the part on creating state via closures. What's starting to concern me about this is the difficulty of preserving state of components which is what I'm really after. We can pass signals all the way to SiblingComponent and get the behaviours wanted in this example. 

We lose all that when we start creating more complex components that wrap BrokenComponent. As soon as you drive those wrapper components with signals on their attributes, you get the same unwanted component recreation.

```javascript
var signal = S.data("World");
document.body.appendChild(
    (function() {
        var __, __div1, __div1_insert2, __button2, __insert3;
        __ = Surplus.createElement("div", null, null);
        __div1 = Surplus.createElement("div", null, __);
        Surplus.createTextNode("Hello ", __div1);
        __div1_insert2 = Surplus.createTextNode("", __div1);
        __button2 = Surplus.createElement("button", null, __);
        __insert3 = Surplus.createTextNode("", __);
        Surplus.S(function(__range) { return Surplus.insert(__range, signal()); }, {
            start: __div1_insert2,
            end: __div1_insert2,
        });
        Surplus.S(function() {
            __button2.onclick = ev => signal("Bob");
            __button2.textContent = "Change name to Bob";
        });
        Surplus.S(function(__range) {
            return Surplus.insert(__range, BrokenComponent({
                "signal": signal
            }));
        }, { start: __insert3, end: __insert3 });
        return __;
    })()
)

function BrokenComponent({ signal }) {
    console.log("Should only see this message once");
    return [
        Surplus.createElement('div', null, null),
        SiblingComponent({
            "name": signal()
        })
    ];
}

function FixedComponent({ signal }) {
    console.log("Should only see this message once");
    // fixed by adding a div around <SecondChildComponent/>
    return [
        Surplus.createElement('div', null, null),
        (function() {
            var __, __insert1;
            __ = Surplus.createElement('div', null, null);
            __insert1 = Surplus.createTextNode('', __)
            Surplus.S(function(__range) {
                return Surplus.insert(__range, SiblingComponent({
                    "name": signal()
                }));
            }, { start: __insert1, end: __insert1 });
            return __;
        })()
    ];
}

function SiblingComponent({ name }) {
    console.log("I'm always recreated")
    return (function() {
        var __;
        __ = Surplus.createElement('div', null, null);
        Surplus.content(__, name, "");
        return __;
    })()
}
```

FixedComponent
```javascript
var signal = S.data("World");
document.body.appendChild(
    (function() {
        var __, __div1, __div1_insert2, __button2, __insert3;
        __ = Surplus.createElement("div", null, null);
        __div1 = Surplus.createElement("div", null, __);
        Surplus.createTextNode("Hello ", __div1);
        __div1_insert2 = Surplus.createTextNode("", __div1);
        __button2 = Surplus.createElement("button", null, __);
        __insert3 = Surplus.createTextNode("", __);
        Surplus.S(function(__range) { return Surplus.insert(__range, signal()); }, {
            start: __div1_insert2,
            end: __div1_insert2,
        });
        Surplus.S(function() {
            __button2.onclick = ev => signal("Bob");
            __button2.textContent = "Change name to Bob";
        });
        Surplus.S(function(__range) {
            return Surplus.insert(__range, BrokenComponent({
                "signal": signal
            }));
        }, { start: __insert3, end: __insert3 });
        return __;
    })()
)
```

**Comment by ryansolid** [comment]
I guess the question is where are you using the values of these signals if not in a computation whether created manually or automatically as a DOM binding. Even if a parent component needs some of it's bindings re-evaluated it isn't guarenteed to re-execute everything. If you straight out call signal() you are going to force re-evaluation of the current computation but this is always avoided by nesting in it's own computation.

Like:
``` js
const signal = S.data('init');

S(() => {
    console.log('evaluates once');
    S(() => {
        signal()
        console.log('evaluates twice')
    })
})

signal('updated')
```
You can have as many inner computations as you want without it re-evaluating the outer one. However, when the outer one re-evaluates it will re-run everything. If you needed something more complicated like say a parent component has the option of appending an honorific onto the name (ie. "Mr. " + name) you would just pass the computation  instead as a prop.. Ie..

``` js
<BrokenComponent name={S(() => showHonorific() ? 'Mr. ' + signal()  :  signal())} />
```
I suppose the library could be doing that automatically, but I think that would force all props would have to be treated as Signals (you wouldn't be able to pass basic values). The difference with DOM bindings is that the computation ends up doing the side-effect write to the underlying element so you no longer are interfacing with it.

When I first found the library this whole thing crossed my mind briefly since I felt without constant vigilance there is risk of accidentally triggering unexpected recalcs. The thing is where in other similarish libraries you wouldn't be able to nest so freely, the smart garbage collection employed here makes it fairly trivial so I believe it's the encouraged pattern. It's just signals/computations all the way down.

**Comment by adamhaile** [comment]
Yeah, as Ryan said, Surplus doesn't have React's layer of first-class stateful components.  Instead, what looks like a component is just syntactic sugar for a function call.  To control update granularity, you put your signal dereferences higher or lower in the call stack (more specifically the tree of computations).  Usually, lower is what you want, to get fine-grained updates.  The important part for preserving state is that the state must be created higher than the point at which it's modified, or else it auto-invalidates itself.

An example -- which may not help your particular case, since you're returning arrays.  Say you wanted a component that showed a button until you clicked it, at which point it said "hi."  The following *wouldn't* work:

```jsx
const SayHi = () => {
    const clicked = S.data(false);
    return clicked() ? <span>"hi"</span> : <button onClick={() => clicked(true)}>click me</button>;
}
```

`clicked()` is both created and read in the same context, meaning that as soon as it's modified, the component is recreated, generating a new `clicked()` signal that starts again with the default value `false`.

The problem is in the definition of <SayHi/>: it wants to be stateful -- record whether it's been clicked -- but it returns a node.  It can't change that node once its state changes -- it's already been returned -- so it can't really do what we want it to.

Instead, <SayHi/> should return a node signal, like so:

```jsx
const SayHi = () => {
    const clicked = S.data(false);
    return S(() => clicked() ? <span>"hi"</span> : <button onClick={() => clicked(true)}>click me</button>);
}
```

Now it can change the node when `clicked()` changes.  (Much of the time, you don't need to call the S() constructor in a component like <SayHi/>.  You can just return a thunk -- `() => ...` -- and it will get instantiated at the point at which it's inserted into the DOM.)

This approach is a bit trickier in your case b/c you're returning an array.  Surplus currently unwraps top-level functions about to be inserted into the DOM, but it doesn't do that for functions within an array.  I could consider adding that -- have to think if there were any ramifications.  In your case, that would allow your component to be written as:

```jsx
  function ThunkFixedComponent({signal}) {
    console.log("Should only see this message once");
    return [
      <div/>,
      () => <SiblingComponent name={signal()}/>
    ];
  }
```

**Comment by derekhawker** [comment]
> I suppose the library could be doing that automatically, but I think that would force all props would have to be treated as Signals (you wouldn't be able to pass basic values). The difference with DOM bindings is that the computation ends up doing the side-effect write to the underlying element so you no longer are interfacing with it.

> When I first found the library this whole thing crossed my mind briefly since I felt without constant vigilance there is risk of accidentally triggering unexpected recalcs. The thing is where in other similarish libraries you wouldn't be able to nest so freely, the smart garbage collection employed here makes it fairly trivial so I believe it's the encouraged pattern. It's just signals/computations all the way down. 

Thanks for the explanation and the example. I spent part of the afternoon experimenting with S computations and nested components and I agree. The runtime is very good at managing updates and I didn't have any problems with unexpected renders when I tried lot of contrived examples with multiple depth components. 

Passing signals through nested components is actually one of my favourite things now about Surplus + S.js. There's a few React components I've rewritten for fun and it's interesting to see how much state is removed and prop callbacks are deleted using just a few manipulation on a signal.

**Comment by derekhawker** [comment]
> This approach is a bit trickier in your case b/c you're returning an array. Surplus currently unwraps top-level functions about to be inserted into the DOM, but it doesn't do that for functions within an array. I could consider adding that -- have to think if there were any ramifications. In your case, that would allow your component to be written as...

The main reason I posted it was because of how unintuitive it seems. The intent with the second example below is to create the same DOM as the first example. I could imagine someone refactoring the first code when they started adding more features and wanted to isolate its state. Feels odd that the second example behaves differently because it's in an array

http://jsfiddle.net/jvfxc67p/
View the console output. Will display "Other" once, then every .2s will print "Bla World" with "World" alternating with "bob"
```jsx
let sig = S.data("world");

setInterval(() => sig(S.sample(sig) === "world" ? "bob" : "world"), 200);
document.body.appendChild(
    <div>
        <Other/>
        <Bla signal={sig()}/>
    </div>);

function Other() {
    console.log("Other");
    return <div>Other</div>;
}

function Bla(props) {
    console.log("Bla " + props.signal);
    return <div>Bla</div>;
}
```
http://jsfiddle.net/0qojbhme/
View the console output. Every .2s will print "Other" and  "Bla World", repeats.

```jsx
document.body.appendChild(
    <div>
        <ArrayComp/>
    </div>);

function ArrayComp() {
    let signal = S.data("world");
    setInterval(() => signal(S.sample(signal) === "world" ? "bob" : "world"), 200);

    return [
        <Other/>,
        <Bla signal={signal()}/>,
    ];
}

function Other() {
    console.log("Other");
    return <div>Other</div>;
}

function Bla(props) {
    console.log("Bla " + props.signal);
    return <div>Bla</div>;
}
```

**Comment by adamhaile** [comment]
Hi Derek --
Sorry for a slow reply.

The short of it is, yep, this is a corner of the syntax that can be a bit unintuitive.  It comes from adopting a syntax, JSX, that wasn't originally written with Surplus in mind.  In React, lower- and upper-cased components have similar semantics, but in Surplus, they're very different things.  One is a language for defining DOM nodes, and the other is syntactic sugar for a plain function call.

I actually considered not supporting the upper-cased syntax at all with Surplus because of this exact issue: the syntactic sugar doesn't buy us much, so why add it, why not just write the function call.  I also considered adding it but automatically wrapping upper-cased components in S computations, so that they each had their own update granularity.  For the moment, I discarded the first because it would really impinge upon code sharing to/from React, which is otherwise pretty good right now.  For the second, the extra wrapping would make all invocations pay its cost while only being needed in a small number of cases.  It would also break our Typescript typings, which I personally find quite useful.  So for the time being, it's still just a function call, and I occasionally need to do the computation (or often just lambda) wrapping where needed.

If you have advice for language that would make this clearer in the README, let me know!
-- Adam

**Comment by derekhawker** [comment]
Sorry, I saw the email notification, but got busy and forgot to come back. I understand the reasoning and why it's not worth adding a preventative s computation that'd just be adding redundant bloat in 99% of use cases. It bums me out a little since it shows the JSX to be a bit of a leaky abstraction here. Not enough to outweigh the benefits for me though.

I'm not sure about how to put this in the readme. It seems to require an understanding of how Surplus looks beneath the abstraction which seems out of place in a README targeting new users. At least for now it's documented here should anyone come across a similar misunderstanding.

I'll close the issue and thanks again to you both for explaining the issues.
