### ISSUE TITLE
Latest mixin usage( fns)

### ISSUE THREAD

**Issue by ismail-codar** [adamhaile/surplus#8]
Hi @adamhaile now I see that `{...mixin()}` changes to `fn={mixin}`. But this version seems to not typescript friendly!

Example code:
```js
<a fn={mixin1} fn={mixin2} />
```
This error can be fix with editing `interface IntrinsicElements `
`TS2559: Type '{ fn: (el: any) => string; }' has no properties in common with type 'HTMLAttributes<HTMLAnchorElement>'.`

But this seems to be a bigger problem.
TS17001:  `JSX elements cannot have multiple attributes with the same name`

**Comment by ismail-codar** [comment]
I think the previous usage (`{...mixin}`) was better.

**Comment by adamhaile** [comment]
Hi Ismail --
Whoops, yep, I was playing around with whether to name the new attribute `fn={ }` or `S={ }` and the .d.ts I pushed still has `S={ }`.  I'll push a fix.  Good catch!.

On the multiple attributes question, my plan is to provide `fn1`/`fn2`/`fn3` etc as aliases for `fn`, for situations, like typescript and some linters, where multiple attributes of the same name are forbidden.

The overloaded spread syntax, where `{... }` could mean either a function or a property object, caused a lot of complexity in the runtime and made a lot of ahead-of-time compilation optimizations impossible.  The two uses are similar in the sense that they're both open-ended ways to modify a node, but their mechanism is completely different.  Using the same syntax for both meant that I had to detect at runtime what type had been supplied and apply it correctly.  That runtime check had a non-zero perf cost, especially for mixins, where I saw as much as a 2x slowdown in some tests.  There's also a big headache if a user supplies a function during one update but a property object in the next, like `<div {... foo() ? someFn : { id: "bar" } }/>`.  Being explicit makes the intent clearer to the user AND to the compiler, letting it optimize accordingly.

I'm not thrilled with the `fn={...}` attribute-like syntax, but within the confines of JSX, it's the best compromise I could think of.  In the original surplus syntax, mixins were designated by the '@' character, just like with ES7 decorators.  So your example would be `<a @mixin1 @mixin2 />`.

Typescript sees benefits from the split too.  The `{... }` syntax for mixins meant that the supplied function wasn't typechecked.  So you could make a function like `const foo = (v : string) => v.split('.')` then use it as a mixin `<div {...foo} />`.  That would fail at runtime, but typescript said it typed fine, since the function validated against the base-case type signature `{}`.
-- Adam
