### ISSUE TITLE
Missing support for dynamic/string-based tags

### ISSUE THREAD

**Issue by Qix-** [adamhaile/surplus#89]
React's JSX supports the following; Surplus does not seem to.

```javascript
const level = 2;
const H = `h${level}`;
const elem = (
    <H>Hello!</H>
);
```

**Comment by ryansolid** [comment]
This might be an (not worthwhile) effort. The reason it works in React is because it compiles down to `createElement` function for all tags and makes a runtime decision based on whether a string or a function is being passed in. Surplus needs to make the decision at compile time since a Component tags handling is significantly different than an Element. This is the benefit precompilation brings to streamline DOM creation. One could try to trace variable assignment but that could inconsistent. The only way to support this unconditionally would be to hijack every Component function execution adding a check for string and then having a runtime handler for iterating and binding props if it is. Which is all additional and negates most of the benefit of the approach.

**Comment by Qix-** [comment]
You're right. This is more of a problem if trying to dynamically select a built-in tag name as opposed to a custom function-based tag (which would be much easier to reason about).

Here's the work-around:

```javascript
const Tag = ({tag, children, ...rest}) => {
	const elem = document.createElement(tag);
	Surplus.spread(elem, rest);
	elem.append(...children);
	return elem;
};

const level = 1;
<Tag tag={`h${level}`} className="foo">Hello</Tag>
```

Obvious caveat is that it doesn't support function names, but those are much easier to index than the built-in tag names.

**Comment by ryansolid** [comment]
Yeah I've found myself doing similiar things to support Styled Components-esque patterns.
